/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio3;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author joelv
 */
public class Componentes extends javax.swing.JFrame {

    /**
     * Creates new form Componentes
     */
    public Componentes() {
        initComponents();
        updateFont();
        updateColor();
    }

    private void updateFont() {
        jtxtArea.setFont(new Font((String)jspn1.getValue(), Font.PLAIN, (int) jspn2.getValue()));
    }
    
    private void updateColor() {
        Color color = new Color(jsldRed.getValue(), jsldGreen.getValue(), jsldBlue.getValue());
        jtxtArea.setForeground(color);
    }
    
    private void level() {
        String password = new String(jpwdPassword.getPassword());
        int length = password.length();
        jpgbProgress.setValue(length * 5);
        jpgbProgress.setString("Longitud: " + length);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jsldRed = new javax.swing.JSlider();
        jsldGreen = new javax.swing.JSlider();
        jsldBlue = new javax.swing.JSlider();
        jspn1 = new javax.swing.JSpinner();
        jspn2 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtArea = new javax.swing.JTextArea();
        jpwdPassword = new javax.swing.JPasswordField();
        jpgbProgress = new javax.swing.JProgressBar();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jsldRed.setMajorTickSpacing(10);
        jsldRed.setMaximum(255);
        jsldRed.setMinorTickSpacing(5);
        jsldRed.setPaintTicks(true);
        jsldRed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsldRedStateChanged(evt);
            }
        });

        jsldGreen.setMajorTickSpacing(10);
        jsldGreen.setMaximum(255);
        jsldGreen.setMinorTickSpacing(5);
        jsldGreen.setPaintTicks(true);
        jsldGreen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsldGreenStateChanged(evt);
            }
        });

        jsldBlue.setMajorTickSpacing(10);
        jsldBlue.setMaximum(255);
        jsldBlue.setMinorTickSpacing(5);
        jsldBlue.setPaintTicks(true);
        jsldBlue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsldBlueStateChanged(evt);
            }
        });

        jspn1.setModel(new javax.swing.SpinnerListModel(new String[] {"Arial", "Times New Roman"}));
        jspn1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspn1StateChanged(evt);
            }
        });

        jspn2.setModel(new javax.swing.SpinnerNumberModel(12, 8, 80, 1));
        jspn2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspn2StateChanged(evt);
            }
        });

        jtxtArea.setColumns(20);
        jtxtArea.setRows(5);
        jScrollPane1.setViewportView(jtxtArea);

        jpwdPassword.setText("jPasswordField1");
        jpwdPassword.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jpwdPasswordCaretUpdate(evt);
            }
        });

        jFormattedTextField1.setText("jFormattedTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jpgbProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jspn1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jspn2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jsldBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jsldGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jsldRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jsldRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsldGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jspn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jspn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsldBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpwdPassword)
                    .addComponent(jFormattedTextField1)
                    .addComponent(jpgbProgress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jspn1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspn1StateChanged
        // TODO add your handling code here:
        updateFont();
    }//GEN-LAST:event_jspn1StateChanged

    private void jspn2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspn2StateChanged
        // TODO add your handling code here:
        updateFont();
    }//GEN-LAST:event_jspn2StateChanged

    private void jsldRedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsldRedStateChanged
        // TODO add your handling code here:
        updateColor();
    }//GEN-LAST:event_jsldRedStateChanged

    private void jsldGreenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsldGreenStateChanged
        // TODO add your handling code here:
        updateColor();
    }//GEN-LAST:event_jsldGreenStateChanged

    private void jsldBlueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsldBlueStateChanged
        // TODO add your handling code here:
        updateColor();
    }//GEN-LAST:event_jsldBlueStateChanged

    private void jpwdPasswordCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jpwdPasswordCaretUpdate
        // TODO add your handling code here:
        level();
    }//GEN-LAST:event_jpwdPasswordCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Componentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Componentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Componentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Componentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Componentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar jpgbProgress;
    private javax.swing.JPasswordField jpwdPassword;
    private javax.swing.JSlider jsldBlue;
    private javax.swing.JSlider jsldGreen;
    private javax.swing.JSlider jsldRed;
    private javax.swing.JSpinner jspn1;
    private javax.swing.JSpinner jspn2;
    private javax.swing.JTextArea jtxtArea;
    // End of variables declaration//GEN-END:variables
}
