/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Prueba;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.text.DecimalFormat;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.*;

/**
 *
 * @author joelv
 */
public class Componentes extends javax.swing.JFrame {

    /**
     * Creates new form Componentes
     */
    public Componentes() {
        initComponents();
    }
    
    public void Cargar(File selectedFile) {
        DefaultTableModel model = new DefaultTableModel();
        tblTabla.setModel(model);
        try (FileInputStream fis = new FileInputStream(selectedFile);
            Workbook workbook = new HSSFWorkbook(fis)) {

            Sheet sheet = workbook.getSheetAt(0); // Hoja de trabajo (puedes cambiar el índice si hay varias hojas)

            int rowCount = sheet.getPhysicalNumberOfRows();

            if (rowCount > 0) {
                Row headerRow = sheet.getRow(0); // Encabezados
                int columnCount = headerRow.getPhysicalNumberOfCells();

                for (int col = 0; col < columnCount; col++) {
                    model.addColumn(headerRow.getCell(col).toString());
                }

                for (int row = 1; row < rowCount; row++) {
                    Row dataRow = sheet.getRow(row);
                    Object[] rowData = new Object[columnCount];

                    for (int col = 0; col < columnCount; col++) {
                        Cell cell = dataRow.getCell(col);
                        rowData[col] = cell.toString();
                    }

                    model.addRow(rowData);
                }
            }
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar el archivo de Excel.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vacaTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        vacaTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabla = new javax.swing.JTable();
        vacaBoton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vacaTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vacaTextField1ActionPerformed(evt);
            }
        });
        vacaTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                vacaTextField1KeyTyped(evt);
            }
        });

        jLabel1.setText("Solo Mayúsculas");

        vacaTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                vacaTextField2FocusLost(evt);
            }
        });
        vacaTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vacaTextField2ActionPerformed(evt);
            }
        });
        vacaTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                vacaTextField2KeyTyped(evt);
            }
        });

        jLabel2.setText("Solo decimales");

        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTabla);

        vacaBoton1.setText("Cargar Archivo Excel");
        vacaBoton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vacaBoton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addComponent(vacaBoton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(vacaTextField2)
                                    .addComponent(vacaTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vacaTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vacaTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(vacaBoton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vacaTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vacaTextField1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c) && c != 'Ñ') {
            
            evt.setKeyChar(Character.toUpperCase(c));
        } else {
            evt.consume(); // Consume el evento para evitar caracteres no deseados
        }
    }//GEN-LAST:event_vacaTextField1KeyTyped

    private void vacaTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vacaTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vacaTextField2ActionPerformed

    private void vacaTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vacaTextField2KeyTyped
        // TODO add your handling code here:
        if (evt.getKeyChar() != '.' && !Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_vacaTextField2KeyTyped

    private void vacaTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vacaTextField2FocusLost
        // TODO add your handling code here:
        String text = vacaTextField2.getText();
        
        try {
            // Parse the text as a double with two decimal places
            double value = Double.parseDouble(text);
            DecimalFormat decimalFormat = new DecimalFormat("0.00");
            String formattedValue = decimalFormat.format(value);
            vacaTextField2.setText(formattedValue);
        } catch (NumberFormatException ex) {
            // Handle invalid input here, e.g., display an error message
            vacaTextField2.setText("0.00");
        }
    }//GEN-LAST:event_vacaTextField2FocusLost

    private void vacaBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vacaBoton1ActionPerformed
        // TODO add your handling code here:
        java.io.File selectedFile;
                
        JFileChooser fileChooser = new JFileChooser();

        javax.swing.filechooser.FileFilter excelFilter = new javax.swing.filechooser.FileFilter() {
            public boolean accept(File file) {
                String fileName = file.getName().toLowerCase();
                return fileName.endsWith(".xlsx") || fileName.endsWith(".xls") || file.isDirectory();
            }

            public String getDescription() {
                return "Archivos de Excel (*.xlsx, *.xls)";
            }
        };
        
        fileChooser.setFileFilter(excelFilter);
        
        int result = fileChooser.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            // Aquí puedes manejar el archivo seleccionado
            selectedFile = fileChooser.getSelectedFile();
            JOptionPane.showMessageDialog(this, "Archivo seleccionado");
            
        }
        
        
    }//GEN-LAST:event_vacaBoton1ActionPerformed

    private void vacaTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vacaTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vacaTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Componentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Componentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Componentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Componentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Componentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTabla;
    private javax.swing.JButton vacaBoton1;
    private javax.swing.JTextField vacaTextField1;
    private javax.swing.JTextField vacaTextField2;
    // End of variables declaration//GEN-END:variables
}
